---
- name: Execute PowerShell script with environment variables
  hosts: 'windows-inventory'
  gather_facts: false
  tasks:
    - name: Set environment variables
      environment:
        SERVER: "{{ inventory_hostname }}"
        LOAD: "70"
        DRIVE: "C"
        FREESPACE: "10"
        AMOUNT: "4000"
        SERVICENAME: "SMA*"
        MONITOR: "cpu"
        PROCESS: "7zip"
        PORT: "8181"
        DISK: "0"
        PARTITION: "1"
        SIZE: "50"
      become: yes

    - name: Execute PowerShell script
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\path\to\script.ps1 -server $env:SERVER -load $env:LOAD -drive $env:DRIVE -freespace $env:FREESPACE -amount $env:AMOUNT -servicename $env:SERVICENAME -monitor $env:MONITOR -process $env:PROCESS -port $env:PORT -disk $env:DISK -partition $env:PARTITION -size $env:SIZE
      register: script_output

    - name: Print script output
      debug:
        var: script_output.stdout_lines

