---
- name: Execute PowerShell script with environment variables
  hosts: all
  gather_facts: false
  vars:
        server: "{{ inventory_hostname }}"
        load: "70"
        drive: "c"
        freespace: "10"
        amount: "4000"
        servicename: "sma*"
        monitor: "cpu"
        process: "7zip"
        port: "8181"
        disk: "0"
        partition: "1"
        size: "50"

  tasks:
    - name: Execute PowerShell script
      win_shell: powershell.exe -ExecutionPolicy Bypass -File windows_monitors.ps1 -server {{server}} -load {{load}} -drive {{drive}} -freespace {{freespace}} -amount {{amount}} -servicename {{servicename}} -monitor {{monitor}} -process {{process}} -port {{port}} -disk {{disk}} -partition {{partition}} -size {{size}}
      register: script_output

    - name: Print script output
      debug:
        var: script_output.stdout_lines

